// Generated by supabase/functions/_shared/sync-process-job-vendor.mjs. Do not edit directly.
import { getWorkspaceProviderRuntimeConfig } from "../ai/providers.ts"
import { enrichAccountContextWithExa } from "./exa-provider.ts"

export async function enrichAccountContext(input: Parameters<typeof enrichAccountContextWithExa>[0]) {
  const config = await getWorkspaceProviderRuntimeConfig(input.workspaceId, "enrichment")
  const providerId = config?.providerId ?? "exa"

  switch (providerId) {
    case "exa":
      return enrichAccountContextWithExa(input)
    default:
      throw new Error(`Unsupported enrichment provider: ${providerId}`)
  }
}
