// Generated by supabase/functions/_shared/sync-process-job-vendor.mjs. Do not edit directly.
import { anthropic, createAnthropic } from "@ai-sdk/anthropic"
import { createOpenAI, openai } from "@ai-sdk/openai"
import { generateObject } from "ai"
import type { ZodType } from "zod"
import { createAdminClient } from "../supabase/admin.ts"
import { decryptWorkspaceSecret } from "../security/encryption.ts"
import { getProviderRegistryEntry, isProviderRuntimeSupported } from "./provider-registry.ts"
import { readRuntimeEnv } from "../runtime/env.ts"

export type WorkspaceProviderRole = "primary_llm" | "fallback_llm" | "enrichment" | "document_parsing"
export type PlaycallProvider =
  | "openai"
  | "anthropic"
  | "google"
  | "google-vertex"
  | "xai"
  | "mistral"
  | "cohere"
  | "deepseek"
  | "groq"
  | "together"
  | "fireworks"
  | "alibaba"
  | "deepinfra"
  | "cerebras"
  | "huggingface"
  | "baseten"
  | "moonshot"
  | "vercel"

type ProviderRuntimeConfig = {
  providerId: string
  model: string
  credentials: Record<string, unknown>
  metadata: Record<string, unknown>
  enabled: boolean
  source: "env" | "workspace"
}

export const OPENAI_COMPATIBLE_BASE_URLS: Partial<Record<PlaycallProvider, string>> = {
  // Gemini Developer API ships a real OpenAI-compatible /chat/completions
  // surface with plain API-key auth, so it fits this generic path - no need
  // for a dedicated @ai-sdk/google package. Vertex is different (GCP
  // service-account + project/location auth) and stays unsupported.
  google: "https://generativelanguage.googleapis.com/v1beta/openai",
  xai: "https://api.x.ai/v1",
  mistral: "https://api.mistral.ai/v1",
  deepseek: "https://api.deepseek.com/v1",
  groq: "https://api.groq.com/openai/v1",
  together: "https://api.together.xyz/v1",
  fireworks: "https://api.fireworks.ai/inference/v1",
  alibaba: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
  deepinfra: "https://api.deepinfra.com/v1/openai",
  cerebras: "https://api.cerebras.ai/v1",
  huggingface: "https://router.huggingface.co/v1",
  moonshot: "https://api.moonshot.ai/v1",
  vercel: "https://ai-gateway.vercel.sh/v1",
}

function getEnvRuntimeConfig(role: WorkspaceProviderRole): ProviderRuntimeConfig | null {
  if (role === "primary_llm") {
    const openAiApiKey = readRuntimeEnv("OPENAI_API_KEY")?.trim()
    if (openAiApiKey) {
      return {
        providerId: "openai",
        model: "gpt-5-mini",
        credentials: { apiKey: openAiApiKey },
        metadata: {},
        enabled: true,
        source: "env",
      }
    }
  }

  if (role === "fallback_llm") {
    const anthropicApiKey = readRuntimeEnv("ANTHROPIC_API_KEY")?.trim()
    if (anthropicApiKey) {
      return {
        providerId: "anthropic",
        model: "claude-sonnet-4-6",
        credentials: { apiKey: anthropicApiKey },
        metadata: {},
        enabled: true,
        source: "env",
      }
    }

    const openAiApiKey = readRuntimeEnv("OPENAI_API_KEY")?.trim()
    if (openAiApiKey) {
      return {
        providerId: "openai",
        model: "gpt-5-mini",
        credentials: { apiKey: openAiApiKey },
        metadata: {},
        enabled: true,
        source: "env",
      }
    }
  }

  const exaApiKey = readRuntimeEnv("EXA_API_KEY")?.trim()
  if (role === "enrichment" && exaApiKey) {
    return {
      providerId: "exa",
      model: "",
      credentials: { apiKey: exaApiKey },
      metadata: {},
      enabled: true,
      source: "env",
    }
  }

  const theHogAccessKey = readRuntimeEnv("THEHOG_ACCESS_KEY")?.trim()
  const theHogSecretKey = readRuntimeEnv("THEHOG_SECRET_KEY")?.trim()
  if (role === "enrichment" && theHogAccessKey && theHogSecretKey) {
    return {
      providerId: "thehog",
      model: "",
      credentials: { accessKey: theHogAccessKey, secretKey: theHogSecretKey },
      metadata: {},
      enabled: true,
      source: "env",
    }
  }

  const llamaCloudApiKey = readRuntimeEnv("LLAMA_CLOUD_API_KEY")?.trim()
  if (role === "document_parsing" && llamaCloudApiKey) {
    return {
      providerId: "llamaparse",
      model: "",
      credentials: { apiKey: llamaCloudApiKey },
      metadata: {},
      enabled: true,
      source: "env",
    }
  }

  return null
}

export async function getWorkspaceProviderRuntimeConfig(
  workspaceId: string,
  role: WorkspaceProviderRole
): Promise<ProviderRuntimeConfig | null> {
  const admin = createAdminClient()
  const { data, error } = await admin
    .from("workspace_provider_settings")
    .select("provider_type, selected_default_model, enabled, metadata")
    .eq("workspace_id", workspaceId)
    .eq("role", role)
    .maybeSingle()

  if (error) {
    throw error
  }

  if (!data) {
    const envConfig = getEnvRuntimeConfig(role)
    if (envConfig) {
      console.log("[providers] resolved provider config", {
        workspaceId,
        role,
        providerId: envConfig.providerId,
        source: envConfig.source,
      })
    } else {
      console.log("[providers] no provider config found", {
        workspaceId,
        role,
      })
    }
    return envConfig
  }

  const { data: credData } = await admin
    .from("workspace_provider_credentials")
    .select("encrypted_credentials")
    .eq("workspace_id", workspaceId)
    .eq("provider_id", data.provider_type)
    .maybeSingle()

  const config = {
    providerId: data.provider_type,
    model: data.selected_default_model ?? getProviderRegistryEntry(data.provider_type)?.defaultModel ?? "",
    credentials: decryptWorkspaceSecret((credData?.encrypted_credentials as Record<string, unknown> | null) ?? {}),
    metadata: (data.metadata as Record<string, unknown> | null) ?? {},
    enabled: Boolean(data.enabled),
    source: "workspace" as const,
  }

  // A workspace row existing isn't the same as it being usable - e.g. a
  // settings save with the API key field left blank creates an "enabled" row
  // with empty credentials. That used to permanently shadow the env fallback
  // below (since this branch only ran when no row existed at all), silently
  // breaking workspaces that would otherwise work fine off env vars. Treat a
  // row missing one of its required credentials the same as no row.
  if (!hasRequiredCredentials(config.providerId, config.credentials)) {
    const envConfig = getEnvRuntimeConfig(role)
    console.log("[providers] workspace config missing required credentials, falling back to env", {
      workspaceId,
      role,
      providerId: config.providerId,
      envFallbackAvailable: Boolean(envConfig),
    })
    return envConfig
  }

  console.log("[providers] resolved provider config", {
    workspaceId,
    role,
    providerId: config.providerId,
    source: config.source,
    enabled: config.enabled,
  })

  return config
}

function hasRequiredCredentials(providerId: string, credentials: Record<string, unknown>) {
  const registryEntry = getProviderRegistryEntry(providerId)
  if (!registryEntry) {
    return true
  }

  return registryEntry.credentialFields
    .filter((field) => field.required)
    .every((field) => {
      const value = credentials[field.key]
      return typeof value === "string" && value.trim().length > 0
    })
}

// Onboarding lets a manager skip provider setup (Steps 2-4) and land in the
// dashboard anyway - the proxy gate only checks that a workspace membership
// exists, not that setup actually finished. That's a deliberate "let them
// look around first" choice, but it means a fully-skipped workspace looks
// identical to a configured one until a manager tries to actually create a
// playbook or score a call and it fails. Surface what's missing so the
// dashboard can warn before that happens, rather than after.
export async function getMissingRequiredProviderRoles(workspaceId: string): Promise<WorkspaceProviderRole[]> {
  const requiredRoles: WorkspaceProviderRole[] = ["primary_llm", "enrichment", "document_parsing"]
  const configs = await Promise.all(requiredRoles.map((role) => getWorkspaceProviderRuntimeConfig(workspaceId, role)))
  return requiredRoles.filter((_, index) => configs[index] === null)
}

function createOpenAICompatibleModel(
  providerId: PlaycallProvider,
  credentials: Record<string, unknown>,
  modelId: string
) {
  const apiKey = typeof credentials.apiKey === "string" ? credentials.apiKey.trim() : ""
  const explicitBaseUrl = typeof credentials.baseUrl === "string" ? credentials.baseUrl.trim() : ""
  const baseURL = explicitBaseUrl || OPENAI_COMPATIBLE_BASE_URLS[providerId]

  if (!apiKey || !baseURL) {
    throw new Error(`Missing API key or base URL for provider ${providerId}`)
  }

  const provider = createOpenAI({
    name: providerId,
    apiKey,
    baseURL,
  })

  return provider(modelId)
}

export function getLanguageModel(provider: PlaycallProvider, model = "") {
  if (provider === "anthropic") {
    return anthropic(model || "claude-sonnet-4-6")
  }

  return openai(model || "gpt-5-mini")
}

function getLanguageModelFromRuntimeConfig(config: ProviderRuntimeConfig) {
  const providerId = config.providerId as PlaycallProvider

  if (!isProviderRuntimeSupported(providerId)) {
    throw new Error(`Provider ${providerId} is not enabled in the current runtime`)
  }

  if (providerId === "openai") {
    const apiKey = typeof config.credentials.apiKey === "string" ? config.credentials.apiKey.trim() : undefined
    const provider = createOpenAI({
      apiKey,
      name: "openai",
    })
    return provider(config.model || "gpt-5-mini")
  }

  if (providerId === "anthropic") {
    const apiKey = typeof config.credentials.apiKey === "string" ? config.credentials.apiKey.trim() : undefined
    if (!apiKey) {
      throw new Error("Missing Anthropic API key")
    }
    const provider = createAnthropic({ apiKey, name: "anthropic" })
    return provider(config.model || "claude-sonnet-4-6")
  }

  return createOpenAICompatibleModel(providerId, config.credentials, config.model)
}

export async function resolveWorkspaceLanguageModel(input: {
  workspaceId: string
  requiredCapabilities: string[]
}) {
  const primary = await getWorkspaceProviderRuntimeConfig(input.workspaceId, "primary_llm")
  const fallback = await getWorkspaceProviderRuntimeConfig(input.workspaceId, "fallback_llm")

  const candidates = [primary, fallback].filter((candidate): candidate is ProviderRuntimeConfig => Boolean(candidate?.enabled))

  let lastError: Error | null = null

  for (const candidate of candidates) {
    const registryEntry = getProviderRegistryEntry(candidate.providerId)
    const hasCapabilities = input.requiredCapabilities.every((capability) =>
      registryEntry?.capabilityFlags.includes(capability)
    )

    if (!hasCapabilities) {
      continue
    }

    try {
      return {
        providerId: candidate.providerId,
        modelId: candidate.model,
        source: candidate.source,
        model: getLanguageModelFromRuntimeConfig(candidate),
      }
    } catch (error) {
      lastError = error instanceof Error ? error : new Error("Unable to resolve language model")
    }
  }

  if (lastError) {
    throw lastError
  }

  throw new Error("No configured LLM provider satisfies the required capabilities")
}

export async function generateStructuredObject<T>({
  workspaceId,
  schema,
  prompt,
  schemaName,
  schemaDescription,
}: {
  workspaceId: string
  schema: ZodType<T>
  prompt: string
  schemaName: string
  schemaDescription: string
}) {
  const resolved = await resolveWorkspaceLanguageModel({
    workspaceId,
    requiredCapabilities: ["object_generation", "tool_usage"],
  })

  const result = await generateObject({
    model: resolved.model,
    mode: "tool",
    schema,
    schemaName,
    schemaDescription,
    prompt,
  })

  return {
    providerId: resolved.providerId,
    modelId: resolved.modelId,
    source: resolved.source,
    object: result.object,
  }
}
